# Generated by Django 5.0.7 on 2024-11-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_saveddatasetsfromuser_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateAlgorithmOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_name",
                    models.CharField(default="", max_length=32, verbose_name="算法名"),
                ),
                (
                    "file_path",
                    models.CharField(
                        default="", max_length=255, verbose_name="算法源文件存放路径"
                    ),
                ),
                (
                    "algorithm_type",
                    models.CharField(default="", max_length=32, verbose_name="算法类型"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="算法所有者",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="privatealgorithmofuser",
            constraint=models.UniqueConstraint(
                fields=("owner", "algorithm_name"), name="unique_owner_algorithm"
            ),
        ),
    ]
