# Generated by Django 5.0.7 on 2024-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_privatealgorithmofuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatealgorithmofuser",
            name="model_filepath",
            field=models.CharField(default="", max_length=255, verbose_name="模型文件存放路径"),
        ),
    ]
