# Generated by Django 5.0.7 on 2024-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_privatealgorithmofuser_model_filepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddatasetsfromuser",
            name="multiple_sensors",
            field=models.BooleanField(default=False, verbose_name="是否为多传感器数据"),
        ),
    ]
