# Generated by Django 5.0.7 on 2024-12-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_saveddatasetsfromuser_multiple_sensors"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatealgorithmofuser",
            name="alias",
            field=models.CharField(default="", max_length=32, verbose_name="算法别名"),
        ),
        migrations.AddField(
            model_name="privatealgorithmofuser",
            name="statement",
            field=models.TextField(default="无", verbose_name="算法描述"),
        ),
    ]
