# Generated by Django 5.0.7 on 2024-12-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_privatealgorithmofuser_alias_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatealgorithmofuser",
            name="algorithm_name",
            field=models.CharField(default="", max_length=256, verbose_name="算法名"),
        ),
        migrations.AlterField(
            model_name="privatealgorithmofuser",
            name="alias",
            field=models.CharField(default="", max_length=256, verbose_name="算法别名"),
        ),
    ]
