# Generated by Django 5.0.7 on 2024-12-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_privatealgorithmofuser_algorithm_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddatasetsfromuser",
            name="publicity",
            field=models.BooleanField(default=False, verbose_name="是否公开可见"),
        ),
    ]
