# Generated by Django 5.0.7 on 2024-12-11 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0010_saveddatasetsfromuser_publicity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(default="", verbose_name="反馈的问题")),
                (
                    "module",
                    models.CharField(
                        default="unknown", max_length=64, verbose_name="反馈的模块"
                    ),
                ),
                (
                    "datafile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.saveddatasetsfromuser",
                        verbose_name="反馈的数据id",
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.savedmodelfromuser",
                        verbose_name="反馈的模型id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="反馈者",
                    ),
                ),
            ],
        ),
    ]
