# Generated by Django 5.0.7 on 2024-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="datafile_id",
            new_name="datafile",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="model_id",
            new_name="model",
        ),
    ]
