# Generated by Django 5.0.7 on 2024-12-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0012_rename_datafile_id_feedback_datafile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(default="待处理", max_length=16, verbose_name="反馈处理状态"),
        ),
    ]
