# Generated by Django 5.0.7 on 2024-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_feedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddatasetsfromuser",
            name="file_type",
            field=models.CharField(default="未知类型", max_length=16, verbose_name="文件类型"),
        ),
    ]
