# Generated by Django 5.0.7 on 2024-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0014_saveddatasetsfromuser_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmodelfromuser",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="是否公开"),
        ),
        migrations.AddField(
            model_name="savedmodelfromuser",
            name="model_description",
            field=models.TextField(default="无", verbose_name="模型描述"),
        ),
    ]
