# Generated by Django 5.0.7 on 2024-12-17 08:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0015_savedmodelfromuser_is_publish_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishModelsApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="unknown", max_length=32, verbose_name="模型名称"
                    ),
                ),
                (
                    "application_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="申请时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(default="未处理", max_length=16, verbose_name="申请状态"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.savedmodelfromuser",
                        verbose_name="模型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
        ),
    ]
