# Generated by Django 5.0.7 on 2024-12-17 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_publishmodelsapplication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publishmodelsapplication",
            old_name="user",
            new_name="applicant",
        ),
    ]
