# Generated by Django 5.0.7 on 2024-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0017_rename_user_publishmodelsapplication_applicant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedmodelfromuser",
            name="is_publish",
        ),
        migrations.AddField(
            model_name="savedmodelfromuser",
            name="is_published",
            field=models.CharField(default="未发布", max_length=16, verbose_name="发布状态"),
        ),
    ]
