# Generated by Django 5.0.7 on 2024-12-17 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0018_remove_savedmodelfromuser_is_publish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publishmodelsapplication",
            name="application_time",
        ),
        migrations.RemoveField(
            model_name="publishmodelsapplication",
            name="model_name",
        ),
        migrations.AddField(
            model_name="publishmodelsapplication",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="申请时间",
            ),
            preserve_default=False,
        ),
    ]
