# Generated by Django 5.0.7 on 2024-12-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0020_componenttree_modeltype_componentnode_usermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componenttree",
            name="tree_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
