# Generated by Django 5.0.7 on 2024-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0021_alter_componenttree_tree_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="root_node",
            new_name="parent_node",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="model_description",
            field=models.TextField(default="暂无详细描述"),
        ),
    ]
