# Generated by Django 5.0.7 on 2024-12-24 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0023_remove_publishmodelsapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishmodelsapplication",
            name="audition_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AddField(
            model_name="publishmodelsapplication",
            name="auditor",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditor_publish_models_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddField(
            model_name="publishmodelsapplication",
            name="status",
            field=models.CharField(default="未处理", max_length=16, verbose_name="申请状态"),
        ),
        migrations.AlterField(
            model_name="publishmodelsapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_publish_models_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请人",
            ),
        ),
    ]
