# Generated by Django 5.0.7 on 2024-12-24 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0024_publishmodelsapplication_audition_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="user",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="模型建立者",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_published",
            field=models.CharField(default="未发布", max_length=16, verbose_name="发布状态"),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="model_info",
            field=models.JSONField(default=None, verbose_name="模型信息"),
        ),
        migrations.AlterField(
            model_name="componentnode",
            name="disabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="model_description",
            field=models.TextField(default="无", verbose_name="模型描述"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="model_name",
            field=models.CharField(
                default="unknown", max_length=32, verbose_name="模型名称"
            ),
        ),
    ]
