# Generated by Django 5.0.7 on 2024-12-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0026_componentnode_is_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentnode",
            name="is_published",
            field=models.CharField(default="未发布", max_length=16, verbose_name="发布状态"),
        ),
    ]
