# Generated by Django 5.0.7 on 2024-12-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0027_componentnode_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="component_tree",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="parent_node",
        ),
        migrations.AddField(
            model_name="componentnode",
            name="model",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.usermodel",
            ),
        ),
    ]
