# Generated by Django 5.0.7 on 2024-12-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0028_remove_usermodel_component_tree_and_more"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="IntermediateResult",
        # ),
        # migrations.DeleteModel(
        #     name="PreprocessedData",
        # ),
        # migrations.DeleteModel(
        #     name="RegisteredSpeakers",
        # ),
        # migrations.DeleteModel(
        #     name="SavedModels",
        # ),
        migrations.AlterField(
            model_name="feedback",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.usermodel",
                verbose_name="反馈的模型id",
            ),
        ),
        migrations.AlterField(
            model_name="publishmodelsapplication",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.usermodel",
                verbose_name="模型",
            ),
        ),
    ]
