# Generated by Django 5.0.7 on 2024-12-28 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0029_delete_intermediateresult_delete_preprocesseddata_and_more"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="IntermediateResult",
        # ),
        # migrations.DeleteModel(
        #     name="PreprocessedData",
        # ),
        # migrations.DeleteModel(
        #     name="RegisteredSpeakers",
        # ),
        # migrations.DeleteModel(
        #     name="SavedModels",
        # ),
        migrations.AddField(
            model_name="feedback",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="反馈时间",
            ),
            preserve_default=False,
        ),
    ]
