# Generated by Django 5.0.7 on 2025-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0030_delete_intermediateresult_delete_preprocesseddata_and_more"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="SavedModels",
        # ),
        migrations.AlterField(
            model_name="publishmodelsapplication",
            name="create_time",
            field=models.DateTimeField(verbose_name="申请时间"),
        ),
    ]
